r=int(input('Nhap vao ban kinh cua duong tron:'))
Dientich=float(3.14*r**2)
Chuvi=float(2*r*3.14)
print('Dien tich cua duong tron co ban kinh',r,'la = ',round((Dientich),1))
print('Chu vi cua duong tron co ban kinh',r,'la = ',round((Chuvi),1))