a=int(input())
b=int(input())
c=int(input())
d=(c+a*2+b*3)/6
if d>=9: print("Xuat sac")
elif d>=8: print("Gioi")
elif d>=7: print("Kha")
elif d>=6: print("Trung binh Kha")
elif d>=5: print("Trung binh")
elif d>=3: print("Yeu")
else: print("Kem")